name: pokemon_project
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0-35.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  http: ^1.1.0
  google_fonts: ^6.2.1
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.3.2
  win32: ^5.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.1.0

# Configuration pour flutter_icons
flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon.png"

# Configuration pour flutter_native_splash
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/splash.png
  android_12:
    image: assets/splash.png
    color: "#FFFFFF"

# Configuration Flutter
flutter:
  uses-material-design: true
  
  assets:
    - assets/pokemon-logo.png
    - assets/pokeball.png
  
  #fonts:
  #  - family: PressStart2P
  #    fonts:
  #      - asset: assets/fonts/PressStart2P-Regular.ttf